version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony-rest-api
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./../app:/var/www/app

  server:
    container_name: server
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./../app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf